language: java
dist: trusty

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jdk:
  - oraclejdk8
  - openjdk8

branches:
  only:
  - master
  - Develop
  - TravisCI

after_success:
- mvn clean cobertura:cobertura coveralls:report
